server:
  port: 7071

image:
  path: C:\Users\pooya\Desktop\New folder\
  url: http://localhost:7070/image/download/

# DB
spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/imageSave
  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    path: /
    name: LoggingInfo.txt
