// Test generated by RoostGPT for test java-sping-test2 using AI Type Vertex AI and AI Model text-bison

package com.pooyafils.uploaddownloading.services;

import com.pooyafils.uploaddownloading.domain.MyFile;
import com.pooyafils.uploaddownloading.repository.MyFileRepository;
import org.apache.commons.io.IOUtils;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@ExtendWith(SpringExtension.class)
@SpringBootTest
public class FileService_getImageById_2156d66f2b_Test {

    @Mock
    private MyFileRepository repository;

    @InjectMocks
    private FileService fileService;

    @Test
    public void test_getImageById_success() throws IOException {
        // given
        MyFile myFile = new MyFile();
        myFile.setId(1);
        myFile.setName("test.jpg");
        myFile.setSize(100);
        myFile.setContentType("image/jpeg");
        Path path = Paths.get("src/test/resources/test.jpg");
        byte[] fileContent = Files.readAllBytes(path);
        myFile.setContent(fileContent);

        when(repository.findById(1)).thenReturn(myFile);

        // when
        MyFile result = fileService.getImageById(1);

        // then
        assertEquals(myFile, result);
    }

    @Test
    public void test_getImageById_notFound() throws IOException {
        // given
        when(repository.findById(1)).thenReturn(null);

        // when
        MyFile result = fileService.getImageById(1);

        // then
        assertEquals(null, result);
    }
}
