// Test generated by RoostGPT for test java-sping-test2 using AI Type Open AI and AI Model gpt-4

package com.pooyafils.uploaddownloading.services;

import com.pooyafils.uploaddownloading.domain.MyFile;
import com.pooyafils.uploaddownloading.repository.MyFileRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import java.util.Optional;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.Mockito.when;

public class FileService_getImageById_2e4d0c709d_Test {

    @InjectMocks
    private FileService fileService;

    @Mock
    private MyFileRepository repository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetImageById_Success() {
        MyFile expectedFile = new MyFile();
        expectedFile.setId(1);
        expectedFile.setName("Test Image");
        when(repository.findById(1)).thenReturn(Optional.of(expectedFile));
        MyFile actualFile = fileService.getImageById(1);
        assertEquals(expectedFile, actualFile);
    }

    @Test
    public void testGetImageById_Failure() {
        when(repository.findById(1)).thenReturn(Optional.empty());
        MyFile actualFile = fileService.getImageById(1);
        assertNull(actualFile);
    }
}
