// Test generated by RoostGPT for test java-sping-test2 using AI Type Open AI and AI Model gpt-4

package com.pooyafils.uploaddownloading.services;

import com.pooyafils.uploaddownloading.domain.MyFile;
import com.pooyafils.uploaddownloading.repository.MyFileRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class FileService_getImageById_2e4d0c709d_Test {

    @Mock
    private MyFileRepository repository;

    @InjectMocks
    private FileService fileService;

    @BeforeEach
    public void setUp() {
        MyFile file = new MyFile();
        file.setId(1);
        file.setName("Test Image");
        when(repository.findById(1)).thenReturn(Optional.of(file));
    }

    @Test
    public void testGetImageById_Success() {
        MyFile result = fileService.getImageById(1);
        assertNotNull(result);
        assertEquals(1, result.getId());
        assertEquals("Test Image", result.getName());
        verify(repository, times(1)).findById(1);
    }

    @Test
    public void testGetImageById_NotFound() {
        assertThrows(RuntimeException.class, () -> fileService.getImageById(2));
        verify(repository, times(1)).findById(2);
    }
}
