// Test generated by RoostGPT for test java-sping-test2 using AI Type Open AI and AI Model gpt-4

package com.pooyafils.uploaddownloading.services;

import com.pooyafils.uploaddownloading.domain.MyFile;
import com.pooyafils.uploaddownloading.repository.MyFileRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class FileService_findAllImageUrl_cd65a99b73_Test {

    @InjectMocks
    private FileService fileService;

    @Mock
    private MyFileRepository repository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testFindAllImageUrl() {
        MyFile file1 = new MyFile();
        file1.setId(1L);
        file1.setUrl("http://test1.com");

        MyFile file2 = new MyFile();
        file2.setId(2L);
        file2.setUrl("http://test2.com");

        when(repository.findAll()).thenReturn(Arrays.asList(file1, file2));

        List<MyFile> result = fileService.findAllImageUrl();

        assertEquals(2, result.size());
        assertEquals(file1, result.get(0));
        assertEquals(file2, result.get(1));
    }

    @Test
    public void testFindAllImageUrl_NoData() {
        when(repository.findAll()).thenReturn(Arrays.asList());

        List<MyFile> result = fileService.findAllImageUrl();

        assertEquals(0, result.size());
    }
}
