// Test generated by RoostGPT for test java-sping-test2 using AI Type Open AI and AI Model gpt-4

package com.pooyafils.uploaddownloading.controller;

import com.pooyafils.uploaddownloading.domain.MyFile;
import com.pooyafils.uploaddownloading.services.FileService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.doNothing;

public class ImageController_deleteById_585aaa6ab7_Test {

    @InjectMocks
    ImageController imageController;

    @Mock
    FileService fileService;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testDeleteById_Success() {
        doNothing().when(fileService).delete(1);
        ResponseEntity responseEntity = imageController.deleteById(1);
        assertEquals(HttpStatus.OK, responseEntity.getStatusCode());
        assertEquals("item has been deleted", responseEntity.getBody());
    }

    @Test
    public void testDeleteById_Failure() {
        doNothing().when(fileService).delete(100);
        ResponseEntity responseEntity = imageController.deleteById(100);
        assertEquals(HttpStatus.OK, responseEntity.getStatusCode());
        assertEquals("item has been deleted", responseEntity.getBody());
    }
}
