// Test generated by RoostGPT for test java-sping-test2 using AI Type Open AI and AI Model gpt-4

package com.pooyafils.uploaddownloading.controller;

import com.pooyafils.uploaddownloading.domain.MyFile;
import com.pooyafils.uploaddownloading.services.FileService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class ImageController_deleteById_585aaa6ab7_Test {

    @Mock
    private FileService service;

    @InjectMocks
    private ImageController controller;

    @BeforeEach
    public void setUp() {
        // Removed the constructor with parameters as it may not exist in the ImageController class
    }

    @Test
    public void testDeleteById_success() {
        int id = 1;
        doNothing().when(service).delete(id);

        ResponseEntity<String> response = controller.deleteById(id);

        verify(service, times(1)).delete(id);
        assertEquals("item has been deleted", response.getBody());
        assertEquals(200, response.getStatusCodeValue());
    }

    @Test
    public void testDeleteById_failure() {
        int id = 2;
        doThrow(new RuntimeException("Item not found")).when(service).delete(id);

        ResponseEntity<String> response = controller.deleteById(id);

        verify(service, times(1)).delete(id);
        assertEquals("item has been deleted", response.getBody());
        assertEquals(500, response.getStatusCodeValue());
    }
}
