// Test generated by RoostGPT for test java-sping-test2 using AI Type Vertex AI and AI Model text-bison

package com.pooyafils.uploaddownloading.controller;

import com.pooyafils.uploaddownloading.domain.MyFile;
import com.pooyafils.uploaddownloading.services.FileService;
import org.junit.jupiter.api.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class ImageController_deleteById_b8a5f08459_Test {

    @Mock
    private FileService service;

    @InjectMocks
    private ImageController controller;

    @Test
    public void testDeleteById_Success() {
        //given
        int id = 1;

        //when
        when(service.delete(id)).thenReturn(true);
        ResponseEntity response = controller.deleteById(id);

        //then
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertEquals("item has been deleted", response.getBody());
    }

    @Test
    public void testDeleteById_Failure() {
        //given
        int id = 1;

        //when
        when(service.delete(id)).thenReturn(false);
        ResponseEntity response = controller.deleteById(id);

        //then
        assertEquals(HttpStatus.INTERNAL_SERVER_ERROR, response.getStatusCode());
        assertEquals("item could not be deleted", response.getBody());
    }
}
