// Test generated by RoostGPT for test java-sping-test2 using AI Type Vertex AI and AI Model text-bison

package com.pooyafils.uploaddownloading.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import javax.persistence.*;
import java.nio.file.FileStore;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

@Data
@Builder
@AllArgsConstructor
@Entity
public class MyFile {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String fileName;

    private String fileType;

    private Long fileSize;

    private FileStore fileStore;

    @Test
    public void testMyFile() {
        MyFile myFile = MyFile.builder()
                .fileName("test.txt")
                .fileType("text/plain")
                .fileSize(100L)
                .fileStore(null)
                .build();

        assertNotNull(myFile);
        assertEquals("test.txt", myFile.getFileName());
        assertEquals("text/plain", myFile.getFileType());
        assertEquals(100L, myFile.getFileSize());
        assertEquals(null, myFile.getFileStore());
    }
}
